# Generated by Django 5.1.4 on 2025-01-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_expensecategorylimit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseCategoryLimit',
        ),
    ]
