# Generated by Django 5.1.4 on 2025-01-19 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_expensecategorylimit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategoryLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transport_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('utility_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('entertainment_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('others_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
